# Generated by Django 4.2.2 on 2023-07-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=256)),
                ('task_path', models.CharField(max_length=256)),
                ('task_args', models.JSONField(default=list)),
                ('task_kwargs', models.CharField(default=dict)),
                ('asked_at', models.DateTimeField(blank=True)),
                ('started_at', models.DateTimeField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
