# Generated by Django 4.2.1 on 2024-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i3tasks', '0002_rename_created_taskexecution_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecutiontry',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecutiontry',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
