# Generated by Django 4.2.1 on 2024-04-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i3tasks', '0003_alter_taskexecutiontry_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecutionresult',
            name='task_execution_try',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='i3tasks.taskexecutiontry'),
        ),
    ]
